version: '3.1'

services:

  wordpress:
    image: wordpress:5.9
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpass
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./data/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/mysql:/var/lib/mysql
